### ISSUE TITLE
about warp field

### ISSUE THREAD

**Issue by rlczddl** [alirezaahmadi/dynamap#1]
It seems that the non rigid part, that is, the warp field, is not added to the main flow,right?

**Comment by alirezaahmadi** [comment]
unfortunately no, it is not completely integrated !, 
but synthetic tests can be found in test runs.

**Comment by rlczddl** [comment]
> unfortunately no, it is not completely integrated !, but synthetic tests can be found in test runs.

I see. Thanks for your reply.
